### ISSUE TITLE
Zaytsev_tool

### ISSUE THREAD

**Issue by grammarware** [researchart/icsme16#11]

**Comment by yasutaka-kamei** [comment]
This artifact provides a tool for the ICSME 2016 paper "The A?B*A Pattern: Undoing Style in CSS and Refactoring Opportunities it Presents." The tool detects instantiations of the A?B∗A pattern smell for CSS code. The paper clearly mentions why the artifact is insightful, useful, and usable.

The tool can be downloaded as a Zip archive. By making use of npm and grunt, it is easy to build and use the tool. Two examples shown in the paper are also helpful to test the tool.

Overall, this artifact is insightful, useful and usable. I would like to recommend "Platinum".

**Comment by mvdbrand** [comment]
The artefact description consists of 2 separate parts, the tool and the data. A combination of
the two would be more appropriate, in the current form the authors had 4 pages to describe their
artefact! 

The description does not contain a clear description of the goal of the artefact. The description
is not really accessible without the original ICSME paper. From the descriptions one can deduce
that the artefact is on refactoring of CCS style files, or the need for refactoring, so called bad 
smells. The A?B*A pattern is actually not explained, and it is impossible to determine the urgency.

The installation and running instructions are clearly and workable. The Example and Output
sections do not really add to the understandability. 

I would classify the artefact description as "? accept" under the condition that the authors
combine the tool and data artefact into one artefact description.

**Comment by grammarware** [comment]
(reopen because Barbara's review is still pending)

**Comment by brusso123** [comment]
Dear authors,

the tool is an insightful, useful, and usable artifact and deserves to be accepted.
It helps researchers in finding the specific code-smell (undoing) in CSS style sheets. The artefact comes with a zip file. The web page of the project seems maintained by a master student and as such the tool updates and maintenance might result uncertain and risky. I would definitely suggest the authors to move it to github or similar open repositories. 
I would suggest to joint this artefact with the dataset artefact presented separately.

The tool application and example of use are provided and fine. label: ? accept, gold

Barbara

**Comment by timm** [comment]
sorry for the accidental "maybe reject".  now fixed.

all reviewers agree "maybe accept". artifact has been labelled accordingly.

**Comment by obaysal** [comment]
@timm I support "accept".
