### ISSUE TITLE
Olga check new words for icsme website

### ISSUE THREAD

**Issue by timm** [researchart/icsme16#2]
As is:

How to Submit

Submissions must be formatted according to the [ICSME 2016 Formatting Instructions](http://icsme2016.github.io/cfp/formatting-instructions.html). Papers must not exceed 2 pages (including all text, references, and figures) plus up to 10 pages that contain ONLY the artifact listing(s). All submissions must be in PDF and must be submitted online by the deadline via the [ICSME 2016 Artifacts Track EasyChair](https://easychair.org/conferences/?conf=icsme2016artifacts) conference management system.

Submission is limited to one per author. Submissions are open to all, but we especially encourage ICSME 2016 authors to offer interesting parts of their work as artifacts. Submissions must not be verbatim materials presented at other venues without or within ICSME 2016 (e.g., it is not permitted to submit the same thing to the ICSME 2016 tool demonstrations track and to the artifacts track). That said, it is valid to submit some augmented part of an ICSME 2016 submission (e.g., scripts used to generate results for an ICSME 2016 research track paper).

As discussed in the [ list of known research artifact types](https://goo.gl/vEoZjd), many research artifacts are shorter than a paper. While we also encourage submissions longer than a paper (e.g., scripts, datasets, executables, virtual images), the track chairs reserve the right to reject without review overly long submissions. If in doubt, email the chairs (tim.menzies@gmail.com and olga.baysal@carleton.ca) prior to submission.

---

To be:

How to Submit, and the Review Process

Write a pdf submissions using the ICSME 2016 Formatting Instructions. This submission would include two (1+1) pages:
1.  First page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria (at http://www.cs.ucdavis.edu/fse2016/calls/artifacts/). This page will be used to evaluate your artifact.
2. Second page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted. The description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures).

Write a pdf submissions using the ICSME 2016 Formatting Instructions. Papers must not exceed 1 page (including all text, references, and figures). Make the name of that pdf “XXX_YYY.pdf”, where XXX is the last name of the corresponding author and YYY is some short name for the artifact.

Get a GitHub account and email that name to icsme2016-artifacts@easychair.org with the subject line: “ICSME16 artifacts track, add my account to the repository.”

Our reply to you will point to a GitHub repository and a directory for submissions. Drag and drop your pdf onto that directory.

Create an issue in that repository whose title is the XXX_YYY. Do not add any text to the comment.

Review of the artifacts will be conducted in GitHub where reviewers’ feedback will be public.

**Comment by obaysal** [comment]
It's good to go. All is fine with me.

**Comment by obaysal** [comment]
Are we keeping Evaluation Badges as "Gold", "Silver", "Bronze", and "Iron"? Then these labels need to match the ones in the master sheet.

**Comment by timm** [comment]
- Will unify to the fse words  (just to keep tom happy)
- revisions sent to the icsme webmaster

**Comment by timm** [comment]
we should close this issue when those revisionsa re udpated

**Comment by obaysal** [comment]
Sounds good! Thanks @timm !
