### ISSUE TITLE
olga: please check invite words

### ISSUE THREAD

**Issue by timm** [researchart/icsme16#3]
olga:

please check i have not cross-pollinated ICSME with any FSE references

note also that our artifacts page has NOT updated yet. so i have sent a hurry up to titus and propose we move our deadline back to june 30.

t

---

Dear ICMSE'16 Author,

Congratulations on the acceptance of your work to ICSME'16. This email is to invite you to submit to the ICSME'16 Artifacts track. Submissions are due June 30.

Note that at ICSME'16 an "artifact" can be many things. 
- For example, executable code could be presented at the demos track (which works best for something with an impressive first impression) or the artifacts track (if the main value of the code is some more nuanced point).
- Also one research paper may contain **many** artifacts (literature review, comments on best statistical methods, etc). So your accepted ICSME'16 paper could actually contain numerous separate artifacts that merit submission to this track.
- For a full list of artifact types, see our https://github.com/researchart/all/blob/master/ListOfArtifacts.md

WHAT TO SUBMIT:

Your submission must be one pdf file containing the following two pages:

First page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria "Insightful", "Useful", "Usable" at http://icsme2016.github.io/cfp/artifacts-track.html.  

Second page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted. This description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures).

HOW TO SUBMIT

Write a pdf submissions using the ICSME 2016 Formatting Instructions.
This submission would include two (1+1) pages:
1.  First page: Describe the artifact along the dimensions of the
   scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation
   criteria (at http://www.cs.ucdavis.edu/fse2016/calls/artifacts/). This
   page will be used to evaluate your artifact.
2. Second page: Describe the artifact and how one can use it (mention
   about any difficulties one might encounter in using the artifact, or
   its maturity relative to the content of the paper). This page will be
   used in the proceedings and you will append it to your research paper
   once the artifact is accepted. The description of the artifact for the
   proceedings must not exceed 1 page (including all text, references,
   and figures).

HOW TO SUBMIT
1. Write the 2 page pdf submissions described above using the ICSME 2016 Formatting Instructions.
2. Make the name of that pdf “XXX_YYY.pdf”, where XXX is the
   last name of the corresponding author and YYY is some short name for
   the artifact.
3. Get a GitHub account and email that name to
   icsme2016-artifacts@easychair.org with the subject line: “ICSME16
   artifacts track, add my account to the repository.”
4. Our reply to you will point to a GitHub repository and a directory for
   submissions. Drag and drop your pdf onto that directory.
5. Create an issue in that repository whose title is the XXX_YYY. Do not
   add any text to the comment.
6. Review of the artifacts will be conducted in GitHub where reviewers’
   feedback will be public.

We look forward to your submission.

Regards,
Olga Baysal,Tim Menzies
(co-chairs, ICSME artifact track).

**Comment by obaysal** [comment]
Dear ICSME 2016 Author,

Congratulations on the acceptance of your work to ICSME 2016! This email is to invite you to submit to the ICSME'16 Artifacts track. Submissions are due July 1.

Note that at ICSME'16 an "artifact" can be many things:
- For example, executable code could be presented at the demos track (which works best for something with an impressive first impression) or the artifacts track (if the main value of the code is some more nuanced point).
- Also one research paper may contain **many** artifacts (literature review, comments on best statistical methods, etc). So your accepted ICSME'16 paper could actually contain numerous separate artifacts that merit submission to this track. For multiple artifacts for a paper, you would need to submit each artifact separately. 
- For a full list of artifact types, see our https://github.com/researchart/all/blob/master/ListOfArtifacts.md

WHAT TO SUBMIT:

Your submission must be one pdf file containing the following two pages:

First page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria "Insightful", "Useful", "Usable" at http://icsme2016.github.io/cfp/artifacts-track.html.  

Second page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted. This description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures).

HOW TO SUBMIT

Write a pdf submissions using the ICSME 2016 Formatting Instructions. This submission would include two (1+1) pages:
1.  First page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria (at http://icsme2016.github.io/cfp/artifacts-track.html). This page will be used to evaluate your artifact.
2. Second page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be
   used in the proceedings and you will append it to your research paper once the artifact is accepted. The description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures).

HOW TO SUBMIT
1. Write the 2 page pdf submissions described above using the ICSME 2016 Formatting Instructions (http://icsme2016.github.io/cfp/formatting-instructions.html).
2. Make the name of that pdf “XXX_YYY.pdf”, where XXX is the last name of the corresponding author and YYY is some short name for the artifact.
3. Get a GitHub account and email that name to icsme2016-artifacts@easychair.org with the subject line: “ICSME16 artifacts track, add my account to the repository.”
4. Our reply to you will point to a GitHub repository and a directory for submissions. Drag and drop your pdf onto that directory.
5. Create an issue in that repository whose title is the XXX_YYY. Do not add any text to the comment.
6. Review of the artifacts will be conducted in GitHub where reviewers’ feedback will be public.

We look forward to your submission!

Regards,

Olga Baysal and Tim Menzies
(co-chairs, ICSME 2016 Artifact Track).

**Comment by obaysal** [comment]
@timm I have updated the wording. 

Question: This track is not limited to the authors of accepted ICSME papers. Do we append artifacts papers to the accepted papers (if authors have an ICSME paper) or do we have separate artifact papers (anyone can submit an artifact paper)? The wording needs to be adjusted on the ICSME CFP Artifacts Track web page then. 

I am fine with moving the submission deadline to June 30.

**Comment by obaysal** [comment]
Updated the submission deadline to July 1 in https://github.com/researchart/icsme16/issues/3#issuecomment-225903664

**Comment by timm** [comment]
> The wording needs to be adjusted on the ICSME CFP Artifacts Track web page then.

where is that wording? i see nothing that says "authors of accepted papers". but then i am old...

t

ps titus pinged re updates on "no abstract"

**Comment by obaysal** [comment]
The following sentence "This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted." no longer holds for the authors who have _not_ submitted any _research papers_ to ICSME.

**Comment by obaysal** [comment]
@timm I will ask you as a General Co-Chair, are we allowed to have standalone artifacts papers at ICSME? Limit is 1 page for these?

**Comment by timm** [comment]
FYI The sentence "This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted." was changed to "This page will be used in the proceedings" 

![image](https://cloud.githubusercontent.com/assets/29195/16096312/5c9492b4-3316-11e6-8a0c-d1902445d434.png)
